language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk8

install: ./gradlew --version
# TO debug
# script: ./gradlew build --debug
script: ./gradlew clean build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/