/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomData service. Represents a row in the &quot;CustomData_CustomData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.custom.data.model.impl.CustomDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.custom.data.model.impl.CustomDataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomData
 * @generated
 */
@ProviderType
public interface CustomDataModel
	extends BaseModel<CustomData>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom data model instance should use the {@link CustomData} interface instead.
	 */

	/**
	 * Returns the primary key of this custom data.
	 *
	 * @return the primary key of this custom data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom data.
	 *
	 * @param primaryKey the primary key of this custom data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this custom data.
	 *
	 * @return the uuid of this custom data
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this custom data.
	 *
	 * @param uuid the uuid of this custom data
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the custom data ID of this custom data.
	 *
	 * @return the custom data ID of this custom data
	 */
	public long getCustomDataId();

	/**
	 * Sets the custom data ID of this custom data.
	 *
	 * @param customDataId the custom data ID of this custom data
	 */
	public void setCustomDataId(long customDataId);

	/**
	 * Returns the group ID of this custom data.
	 *
	 * @return the group ID of this custom data
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this custom data.
	 *
	 * @param groupId the group ID of this custom data
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this custom data.
	 *
	 * @return the company ID of this custom data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this custom data.
	 *
	 * @param companyId the company ID of this custom data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this custom data.
	 *
	 * @return the user ID of this custom data
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this custom data.
	 *
	 * @param userId the user ID of this custom data
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom data.
	 *
	 * @return the user uuid of this custom data
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom data.
	 *
	 * @param userUuid the user uuid of this custom data
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this custom data.
	 *
	 * @return the user name of this custom data
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this custom data.
	 *
	 * @param userName the user name of this custom data
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this custom data.
	 *
	 * @return the create date of this custom data
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom data.
	 *
	 * @param createDate the create date of this custom data
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom data.
	 *
	 * @return the modified date of this custom data
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom data.
	 *
	 * @param modifiedDate the modified date of this custom data
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the custom boolean of this custom data.
	 *
	 * @return the custom boolean of this custom data
	 */
	public boolean getCustomBoolean();

	/**
	 * Returns <code>true</code> if this custom data is custom boolean.
	 *
	 * @return <code>true</code> if this custom data is custom boolean; <code>false</code> otherwise
	 */
	public boolean isCustomBoolean();

	/**
	 * Sets whether this custom data is custom boolean.
	 *
	 * @param customBoolean the custom boolean of this custom data
	 */
	public void setCustomBoolean(boolean customBoolean);

	/**
	 * Returns the custom data of this custom data.
	 *
	 * @return the custom data of this custom data
	 */
	public Date getCustomData();

	/**
	 * Sets the custom data of this custom data.
	 *
	 * @param customData the custom data of this custom data
	 */
	public void setCustomData(Date customData);

	/**
	 * Returns the custom int of this custom data.
	 *
	 * @return the custom int of this custom data
	 */
	public int getCustomInt();

	/**
	 * Sets the custom int of this custom data.
	 *
	 * @param customInt the custom int of this custom data
	 */
	public void setCustomInt(int customInt);

	/**
	 * Returns the custom long of this custom data.
	 *
	 * @return the custom long of this custom data
	 */
	public long getCustomLong();

	/**
	 * Sets the custom long of this custom data.
	 *
	 * @param customLong the custom long of this custom data
	 */
	public void setCustomLong(long customLong);

	/**
	 * Returns the custom string of this custom data.
	 *
	 * @return the custom string of this custom data
	 */
	@AutoEscape
	public String getCustomString();

	/**
	 * Sets the custom string of this custom data.
	 *
	 * @param customString the custom string of this custom data
	 */
	public void setCustomString(String customString);

}