package sample.model.listener;

import org.osgi.service.component.annotations.Component;

import com.liferay.portal.ModelListenerException;
import com.liferay.portal.model.BaseModelListener;
import com.liferay.portal.model.Layout;
import com.liferay.portal.model.ModelListener;

@Component(
	immediate = true,
	service = ModelListener.class
)
public class CustomLayoutListener extends BaseModelListener<Layout> {


	@Override
	public void onBeforeCreate(Layout model)
		throws ModelListenerException {

		System.out.println("About to create layout: " + model.getNameCurrentValue());

		model.setTitle("Title generated by model listener!");

	}
}
